### PR TITLE
Bump to 0.7.1

### PR DESCRIPTION
**Pull request by scuendet**

### CODE REVIEW

**Comment by scuendet** [comment]
:+1:

**Comment by bboe** [comment]
Is it common to start the patch version at 1 and not 0?

**Comment by brynjargr** [comment]
Short answer: no
Long answer: http://semver.org/

**Comment by scuendet** [comment]
There is a 0.7.0 version (see https://rubygems.org/gems/rentlinx), which is why this one is the 0.7.1. The commit for the 0.7.0 seems to have been lost though.

**Comment by brynjargr** [comment]
Ok, that makes sense. However, a little concerning if we lost a commit that was already on master. Did we lose any other commits? Are we following our normal gem development workflow for this gem?

**Comment by scuendet** [comment]
What's our normal gem development workflow?
The commit was lost per se. What probably happend (I _think_) is that I created a new branch to bump the version, bumped the version, pushed it to rubygems, but forgot to merge the branch with master.

**Comment by brynjargr** [comment]
This is our normal workflow, I'm not sure if any of the steps need to be modified for an open source gem, but I don't think so:
https://github.com/appfolio/dev_utils/wiki/Gem-Development-procedures-in-Git

**Comment by scuendet** [comment]
Thanks, I wasn't aware of that page

On Wed, Aug 5, 2015 at 8:30 PM, Brynjar Gretarsson <notifications@github.com

> wrote:
> 
> This is our normal workflow, I'm not sure if any of the steps need to be
> modified for an open source gem, but I don't think so:
> 
> https://github.com/appfolio/dev_utils/wiki/Gem-Development-procedures-in-Git
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/appfolio/rentlinx_client/pull/27#issuecomment-128225423
> .

## 

Sébastien Cuendet

​Senior Software Engineer | AppFolio

## sebastien.cuendet@appfolio.com

Find Us Online --
www.AppFolio.com
www.Facebook.com/AppFolio
www.PropertyManager.com

**Pull request merged**
