### PR TITLE
Add Alabama

### PR DESCRIPTION
**Pull request by XanderStrike**
Congratulations Alabama!

### CODE REVIEW

**Comment by scuendet** [comment]
:+1:

**Comment by bboe** [comment]
What are the extras?

```
2.2.3 :012 > %w(AK AL AR AS AZ CA CO CT DC DE FL GA GU HI IA ID IL IN KS KY LA
2.2.3 :013]>    MA MD ME MI MN MO MP MS MT NC ND NE NH NJ NM NV NY OH OK OR PA
2.2.3 :014]>    PR RI SC SD TN TX UT VA VI VT WA WI WV WY).size
 => 56 
```

**Comment by XanderStrike** [comment]
Rentlinx supports some non-states like American Samoa (AS) and Guam (GU).

**Comment by brynjargr** [comment]
In af_rails we have 60 valid options listed. Are there any in there that we should be including here?
I'm not going to link to it here since this is a public repo and af_rails is private, but I'll send you the link to what I'm talking about.

**Pull request merged**
